### ISSUE TITLE
[Bug]: Make `clusterConfig` optional in ZookeeperCluster CR with default Values

### ISSUE THREAD

**Issue by lwpk110** [zncdatadev/zookeeper-operator#179]
### Duplicates  

I have searched the existing issues  

---

### Summary 💡  

Currently, the `ZookeeperCluster` Custom Resource (CR) **requires** specifying `clusterConfig`, which is not reasonable. If `clusterConfig` is not provided, the system should apply sensible **default values** instead of requiring manual input.  

---

#### **Current Behavior (Issue)**  
The following CR **fails** if `clusterConfig` is not explicitly set:  

```yaml
kind: ZookeeperCluster
metadata:
  apiVersion: zookeeper.kubedoop.dev/v1alpha1
  name: simple-zk
spec:
  clusterConfig:
    listenerClass: external-unstable
```  

#### **Expected Behavior (Fix Proposal)**  
- If `clusterConfig` is **not provided**, reasonable **default values** should be applied automatically.  
- Example **default configuration**:  
  ```yaml
  clusterConfig:
    listenerClass: internal-stable
  ```
  *(This is just an example; actual defaults should align with best practices.)*  

---

### Motivation 🔦  

1. **User Experience**: Avoid forcing users to define `clusterConfig` manually for every ZookeeperCluster instance.  
2. **Flexibility**: Defaults allow quick setup while still permitting customization when needed.  
3. **Consistency**: Other similar configurations often provide default values instead of requiring explicit user input.  

This change would improve usability and reduce configuration overhead.
