### ISSUE TITLE
[Bug]: Status field znodePath not implemented

### ISSUE THREAD

**Issue by lwpk110** [zncdatadev/zookeeper-operator#180]
### Describe the bug

The `status` field `znodePath` is not implemented correctly. After creating the `ZookeeperZnode` custom resource (CR) in Kubernetes, the `status` should update with the corresponding `znodePath` value. Currently, the `znodePath` remains static and does not reflect the actual state after creation.

### Have you searched existing issues?  🔎

No check

### Reproduction

```yaml
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  generation: 1
  name: test-znode
  namespace: kuttl-test-needed-peacock
spec:
  clusterRef:
    name: test-zk
status:
  znodePath: /znode-ac9e905b-4a19-4345-8451-106f623a269b
```

1. Apply the above YAML definition to create a `ZookeeperZnode` resource.
2. Observe that after the resource is created, the `status` field does not update with the actual `znodePath` corresponding to the created znode.

### Logs

```shell
```

### System Info

```shell

```

### Severity

I can work around it
```

This version reflects the issue you're facing and includes the information you've provided, such as the expected behavior and the affected versions.
